name: Test workflow

# Controls when the action will run.
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  myjob:
    runs-on: ubuntu-latest
    steps:
      - run: echo My Job
      - uses: davidbuzinski/actions-test@main
